import type { BlockedResourceKind } from '@shared/types';

/**
 * A curated seed blocklist of common ad, tracker, fingerprinting and
 * cryptomining hosts. Blocking is by registrable domain and all subdomains.
 * Users can extend this at runtime with additional lists (hosts/EasyList).
 */
export const DEFAULT_BLOCKLIST: ReadonlyArray<readonly [string, BlockedResourceKind]> = [
  // Ad networks / exchanges
  ['doubleclick.net', 'ad'],
  ['googlesyndication.com', 'ad'],
  ['googleadservices.com', 'ad'],
  ['adservice.google.com', 'ad'],
  ['2mdn.net', 'ad'],
  ['adnxs.com', 'ad'],
  ['adsystem.amazon.com', 'ad'],
  ['amazon-adsystem.com', 'ad'],
  ['criteo.com', 'ad'],
  ['criteo.net', 'ad'],
  ['rubiconproject.com', 'ad'],
  ['pubmatic.com', 'ad'],
  ['openx.net', 'ad'],
  ['casalemedia.com', 'ad'],
  ['bidswitch.net', 'ad'],
  ['sharethrough.com', 'ad'],
  ['teads.tv', 'ad'],
  ['adform.net', 'ad'],
  ['mathtag.com', 'ad'],
  ['moatads.com', 'ad'],
  ['taboola.com', 'ad'],
  ['outbrain.com', 'ad'],
  ['media.net', 'ad'],
  ['smartadserver.com', 'ad'],
  ['adroll.com', 'ad'],
  ['yieldmo.com', 'ad'],
  ['contextweb.com', 'ad'],
  ['3lift.com', 'ad'],

  // Analytics / trackers
  ['google-analytics.com', 'tracker'],
  ['googletagmanager.com', 'tracker'],
  ['googletagservices.com', 'tracker'],
  ['analytics.google.com', 'tracker'],
  ['connect.facebook.net', 'tracker'],
  ['pixel.facebook.com', 'tracker'],
  ['scorecardresearch.com', 'tracker'],
  ['quantserve.com', 'tracker'],
  ['quantcount.com', 'tracker'],
  ['hotjar.com', 'tracker'],
  ['mouseflow.com', 'tracker'],
  ['fullstory.com', 'tracker'],
  ['mixpanel.com', 'tracker'],
  ['segment.io', 'tracker'],
  ['segment.com', 'tracker'],
  ['amplitude.com', 'tracker'],
  ['heap.io', 'tracker'],
  ['heapanalytics.com', 'tracker'],
  ['chartbeat.com', 'tracker'],
  ['nr-data.net', 'tracker'],
  ['bam.nr-data.net', 'tracker'],
  ['branch.io', 'tracker'],
  ['appsflyer.com', 'tracker'],
  ['adjust.com', 'tracker'],
  ['kochava.com', 'tracker'],
  ['demdex.net', 'tracker'],
  ['everesttech.net', 'tracker'],
  ['omtrdc.net', 'tracker'],
  ['bluekai.com', 'tracker'],
  ['crazyegg.com', 'tracker'],
  ['clarity.ms', 'tracker'],
  ['yandex.ru/metrika', 'tracker'],
  ['mc.yandex.ru', 'tracker'],
  ['stats.wp.com', 'tracker'],

  // Fingerprinters
  ['fingerprintjs.com', 'fingerprinter'],
  ['fpjs.io', 'fingerprinter'],
  ['fingerprint.com', 'fingerprinter'],
  ['iovation.com', 'fingerprinter'],
  ['deviceatlas.com', 'fingerprinter'],

  // Cryptominers
  ['coinhive.com', 'cryptominer'],
  ['coin-hive.com', 'cryptominer'],
  ['cryptoloot.pro', 'cryptominer'],
  ['coinimp.com', 'cryptominer'],
  ['jsecoin.com', 'cryptominer'],
  ['minero.cc', 'cryptominer'],
];
